-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--            local scaleFactor = 1.0
--            local physicsData = (require "shapedefs").physicsData(scaleFactor)
--            local shape = display.newImage("objectname.png")
--            physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
    local physics = { data =
    { 
        
        ["player"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   17.5, -27  ,  21.5, -20  ,  12.5, -26  ,  13.5, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -2.5, 25  ,  -6.5, 21  ,  -6.5, 18  ,  1.5, 22  ,  0.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   38.5, 5  ,  34.5, 9  ,  27.5, 11  ,  28.5, -5  ,  37.5, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   13.5, 15  ,  24.5, -19  ,  28.5, -5  ,  21.5, 13  ,  17.5, 17  ,  14.5, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   21.5, -20  ,  -6.5, 18  ,  7.5, -22  ,  12.5, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -14.5, -25  ,  -27.5, -18  ,  -17.5, -29  ,  -15.5, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -41.5, -1  ,  -39.5, -3  ,  -31.5, -5  ,  -35.5, 10  ,  -41.5, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -8.5, -21  ,  -27.5, -14  ,  -27.5, -18  ,  -14.5, -25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   21.5, 13  ,  28.5, -5  ,  27.5, 11  ,  25.5, 13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -32.5, 10  ,  4.5, -22  ,  -23.5, 13  ,  -28.5, 13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   2.5, -24  ,  4.5, -22  ,  -32.5, 10  ,  -35.5, 10  ,  -8.5, -21  ,  -5.5, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   1.5, 22  ,  -6.5, 18  ,  5.5, 16  ,  3.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -27.5, -14  ,  -8.5, -21  ,  -31.5, -5  ,  -30.5, -10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -23.5, 13  ,  4.5, -22  ,  -8.5, 16  ,  -22.5, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -8.5, -21  ,  -35.5, 10  ,  -31.5, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   5.5, 16  ,  24.5, -19  ,  13.5, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -6.5, 18  ,  21.5, -20  ,  24.5, -19  ,  5.5, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 30, groupIndex = 0 },
                    shape = {   -6.5, 18  ,  -8.5, 16  ,  4.5, -22  ,  7.5, -22  }
                    }
                    
                    
                    
        }
        
        , 
        ["enemy3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -3.5, -29  ,  2.5, -28  ,  2.5, -26  ,  -5.5, -26  ,  -5.5, -28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -5.5, 22  ,  4.5, 21  ,  0.5, 25  ,  -3.5, 25  ,  -5.5, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   6.5, -24  ,  -12.5, -21  ,  -5.5, -26  ,  5.5, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   9.5, -21  ,  -16.5, -20  ,  -12.5, -21  ,  6.5, -24  ,  8.5, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -26.5, -24  ,  -20.5, -20  ,  -30.5, -18  ,  -31.5, -21  ,  -29.5, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   28.5, -21  ,  26.5, -8  ,  16.5, 16  ,  14.5, 19  ,  9.5, 19  ,  17.5, -20  ,  23.5, -24  ,  26.5, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   32.5, 11  ,  16.5, 16  ,  26.5, -8  ,  35.5, -5  ,  38.5, 1  ,  38.5, 7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -5.5, -26  ,  -12.5, -21  ,  -10.5, -25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -30.5, -8  ,  -19.5, 16  ,  -40.5, 9  ,  -41.5, 1  ,  -38.5, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -20.5, -20  ,  13.5, -20  ,  9.5, 19  ,  4.5, 21  ,  -9.5, 20  ,  -19.5, 16  ,  -30.5, -8  ,  -30.5, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -19.5, 16  ,  -9.5, 20  ,  -17.5, 19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -9.5, 20  ,  4.5, 21  ,  -5.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   9.5, 19  ,  13.5, -20  ,  17.5, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   13.5, -20  ,  -16.5, -20  ,  9.5, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   13.5, -20  ,  -20.5, -20  ,  -16.5, -20  }
                    }
                    
                    
                    
        }
        
        , 
        ["enemy1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -10.5, -20  ,  6.5, -21  ,  10.5, -16  ,  21.5, 7  ,  -13.5, -16  ,  -13.5, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -3.5, -29  ,  2.5, -28  ,  -5.5, -26  ,  -5.5, -28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   21.5, -8  ,  19.5, -12  ,  21.5, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   6.5, -21  ,  -10.5, -20  ,  2.5, -26  ,  6.5, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   10.5, -16  ,  6.5, -21  ,  9.5, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -5.5, -26  ,  2.5, -28  ,  2.5, -26  ,  -10.5, -20  ,  -9.5, -24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -19.5, -15  ,  -13.5, -16  ,  21.5, 7  ,  -9.5, 17  ,  -24.5, 7  ,  -24.5, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   26.5, 9  ,  21.5, 7  ,  23.5, -8  ,  24.5, -10  ,  34.5, -8  ,  37.5, -6  ,  38.5, -3  ,  38.5, 4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -41.5, -3  ,  -39.5, -7  ,  -29.5, -10  ,  -24.5, -8  ,  -24.5, 7  ,  -29.5, 9  ,  -41.5, 4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   18.5, 14  ,  6.5, 17  ,  -9.5, 17  ,  21.5, 7  ,  21.5, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -4.5, 25  ,  -7.5, 23  ,  -9.5, 17  ,  6.5, 17  ,  5.5, 21  ,  1.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -24.5, 7  ,  -9.5, 17  ,  -21.5, 14  ,  -24.5, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   19.5, -12  ,  21.5, -8  ,  21.5, 7  ,  10.5, -16  ,  16.5, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   23.5, -8  ,  21.5, 7  ,  21.5, -8  }
                    }
                    
                    
                    
        }
        
        , 
        ["enemy2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   26.5, 18  ,  11.5, 19  ,  35.5, -11  ,  38.5, -9  ,  38.5, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -40.5, -11  ,  -13.5, 19  ,  -30.5, 18  ,  -41.5, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -5.5, 25  ,  -13.5, 19  ,  -40.5, -11  ,  -37.5, -14  ,  -23.5, -15  ,  6.5, 21  ,  2.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -8.5, -28  ,  5.5, -28  ,  8.5, -26  ,  9.5, -19  ,  6.5, 21  ,  -12.5, -19  ,  -11.5, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   -12.5, -19  ,  6.5, 21  ,  -23.5, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   20.5, -15  ,  6.5, 21  ,  9.5, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 5, groupIndex = 0 },
                    shape = {   35.5, -13  ,  35.5, -11  ,  11.5, 19  ,  6.5, 21  ,  20.5, -15  }
                    }
                    
                    
                    
        }
        
        , 
        ["player_bullet"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 2, groupIndex = 0 },
                    shape = {   -5, 15.5  ,  -5, -3.5  ,  -3, -14.5  ,  -2, -16.5  ,  1, -16.5  ,  5, -1.5  ,  5, 15.5  }
                    }
                    
                    
                    
        }
        
        , 
        ["enemy_bullet"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 8, maskBits = 1, groupIndex = 0 },
                    shape = {   5, 2.5  ,  1, 16.5  ,  -2, 16.5  ,  -3, 14.5  ,  -5, 3.5  ,  -5, -15.5  ,  5, -15.5  }
                    }
                    
                    
                    
        }
        
        , 
        ["player_life"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   -5, -7  ,  6, -7  ,  9, 0  ,  4, 3  ,  -4, 3  ,  -9, 0  ,  -9, -4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   9, 0  ,  6, -7  ,  9, -4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   -1, 7  ,  -4, 3  ,  4, 3  ,  1, 7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   4, 3  ,  9, 0  ,  6, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   -9, 0  ,  -4, 3  ,  -6, 3  }
                    }
                    
                    
                    
        }
        
        , 
        ["health_powerup"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   3, 3  ,  -3, -3  ,  8, -3  ,  8, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   -3, 8  ,  -3, -3  ,  3, 3  ,  3, 8  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   -8, -3  ,  -3, -3  ,  -3, 3  ,  -8, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 16, maskBits = 1, groupIndex = 0 },
                    shape = {   3, -8  ,  3, -3  ,  -3, -3  ,  -3, -8  }
                    }
                    
                    
                    
        }
        
    } }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
    
    function physics:get(name)
        return unpack(self.data[name])
    end

    function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
    end
    
    return physics;
end

return M

